# Generated by Django 3.2 on 2021-04-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversationId', models.CharField(blank='False', max_length=255)),
                ('phone_customer', models.CharField(blank='False', max_length=29)),
                ('phone_one', models.CharField(blank='False', max_length=29)),
                ('phone_two', models.CharField(blank='False', max_length=29)),
                ('state', models.IntegerField()),
                ('contactId', models.CharField(blank='False', max_length=255)),
                ('channelId', models.CharField(blank='False', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank='False', max_length=255)),
                ('phone_primary', models.CharField(blank='False', max_length=29)),
            ],
        ),
    ]
